version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - java -version
      - mvn test
      - mvn package
      - ls target
      - mv target/spring-mvc-example.war spring-mvc-example.war
  post_build:
    commands:
      - echo Build completed on `date`
      - ls
artifacts:
  files:
    - spring-mvc-example.war
    - .ebextensions/**/*
